/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/clock.h"
#include "../Inc/usart.h"
#include "../Inc/pwm.h"
#include "../Inc/led.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// Function prototypes
void print_menu(void);

int main(void) {
    SysClockConfig();
    USART2_config();
    LED_init();
    PWM_config();

    char choice;

    while (1) {
        print_menu();
        choice = UART_getchar();
        UART2_SendChar(choice);
        UART2_SendString("\n\r");

        switch (choice) {
            case '1':
                LED_Blinking();
                break;
            case '2':
            	start_PWM_output();
                break;
            case '3':
                UART2_SendString("Exiting utility...\n\r");

                return 0;
            default:
                UART2_SendString("Invalid choice. Please try again.\n\r");
                break;
        }
    }
}

void print_menu(void) {
    UART2_SendString("\n\rMenu:\n\r");
    UART2_SendString("1. Multi-Delay LED Blinking\n\r");
    UART2_SendString("2. LED Intensity control \n\r");
    UART2_SendString("3. Exit\n\r");
    UART2_SendString("Enter your choice: ");
}
